### ISSUE TITLE
Disqus-like comments loading at the bottom of a page

### ISSUE THREAD

**Issue by jonstokes** [sylque/docuss#17]
I'm working on a fast-growing site (theprepared.com), and we're looking to add comments and a forum soon. We're hosted on WordPress, and we want to move away from Disqus for blog and article comments to something we can host ourselves and own the user db (and have a forum with the same user db as the blog/article comments).

I've been a fan of Discourse for a while, and I love what you're doing with docuss. It checks a lot of our boxes for a Disqus replacement, but the main issue right now is the way the comments load in an expandable sidebar. This wouldn't really work with our site design and theme (especially on mobile), and we'd much prefer bottom-loading comments like Disqus.

So I have a few questions:
1. Do you have any plans to implement such a feature any time soon?
2. If so, how can I help? (I'm not as familiar with Ember... My JS skills are more in React. But I can learn).
3. If we were to try to do a big rollout of docuss on theprepared.com, how open/available would you be to working with us on it to really make it a great example of what's possible?

Would love to chat more via email, phone, or in here. You can reach me at jon@theprepared.com.

**Comment by sylque** [comment]
Sorry to be so late on this (it seems I have a notification issue).

> we'd much prefer bottom-loading comments like Disqus. Do you have any plans to implement such a feature any time soon?

This is a recurrent question and I still didn't make up my mind about it. How would such a feature be different from the standard [Embedding Discourse Comments via Javascript](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963)?
