### ISSUE TITLE
In a topic, the timeline overlaps underneath categories

### ISSUE THREAD

**Issue by AndyatFocallocal** [sylque/docuss#4]
with Docuss off the in page scroll bar stops where the thread stops. with Docuss on it overlaps elements below

![image](https://user-images.githubusercontent.com/16229696/61596193-c1a05b00-ac00-11e9-8b99-3f81950adfd5.png)

**Comment by sylque** [comment]
@AndyatFocallocal , would you please send me a link where the problem occurs?

**Comment by sylque** [comment]
@AndyatFocallocal , do you confirm this? On which page? PC or mobile?

**Comment by AndyatFocallocal** [comment]
PC, and all pages once a user reaches the bottom of the comments. it doesn't occur when Docus is switched off. 

here's one url where it occurs: https://publichappinessmovement.com/t/topic/70/24

**Comment by sylque** [comment]
Fixed in 1.0.11
